### ISSUE TITLE
Incorrect Voronoi Diagram for simple test case

### ISSUE THREAD

**Issue by kgoodrick-uu** [d3/d3-delaunay#146]
For a certain array of 5 points the Voronoi diagram "misses" a point. I have reproduced this on [observable](https://observablehq.com/d/02b23af92458f45b).

<img width="260" alt="image" src="https://github.com/user-attachments/assets/081b9a62-70ac-4052-ab56-9255cb88ac75">

I originally reported this as a bug in Vega-Lite Vega/vega-lite#9388 and then Vega Vega/vega#3941, but after more digging I believe the bug is coming from this library.

**Comment by Fil** [comment]
Thanks! I can confirm that this bug comes from the jittering we use to solve collinear points:
https://github.com/d3/d3-delaunay/blob/dc894a162e72eb749fe45909fd4145c5da425fc6/src/delaunay.js#L63

Solved by increasing the factor 1e-8 to 1e-7. However, this in turn breaks another test. I found a sweet spot value at 1.5e-8 that makes all the tests happy, but it's clearly not a great solution (see #147).

**Comment by Fil** [comment]
solved by #147
