### ISSUE TITLE
delaunay.find seems… wrong?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-delaunay#78]
If the small red dot is the target (mouse location), is this the expected search path? It looks like it’s not actually choosing the points that are closest to the mouse while traversing, and I’m not sure if it’s an invalidation triangulation or something else weird. (This is a random 200-point sample of the delaunay.find notebook dataset.)

![image](https://user-images.githubusercontent.com/230541/61254037-29523400-a731-11e9-9648-a1076d6f7dda.png)

**Comment by mbostock** [comment]
Okay, so the notebook’s implementation of delaunay.find was wrong. I have updated it to use delaunay._step and it is now correct. I didn’t investigate what was wrong with the notebook implementation.

**Comment by Fil** [comment]
Thanks!

Another visible issue in this notebook is that point 0 is degenerate (there are two butters in the dataset with the same x,y coordinates), so the first step in the notebook looks weird (because find is jumping arbitrarily to point 1). Not a problem per se but it makes the search path look wrong too, the first step being "backwards". Not sure if we should live with it or set start=1 instead of 0.

![Capture d’écran 2019-07-16 à 06 42 58](https://user-images.githubusercontent.com/7001/61267598-d3b17200-a798-11e9-88b9-81392ffc583c.png)

**Comment by mbostock** [comment]
The other reason that I was surprised is that I was expecting it to follow the straightest line from the source to the target, but the algorithm doesn’t minimize the length of the line—it minimizes the number of hops (the topological distance).

**Comment by Fil** [comment]
The strategy is to jump blindly to a neighbor that is closer to the target — it does not guarantee that minimum. There are often shorter paths, both in total distance and number of hops.

See https://observablehq.com/d/8dc20942c4df82d2 for the three approaches .

**Comment by Fil** [comment]
Sometimes they diverge completely!
<img width="973" alt="Capture d’écran 2019-07-17 à 19 05 42" src="https://user-images.githubusercontent.com/7001/61395541-f5f4de00-a8c5-11e9-8800-9d8803742067.png">

**Comment by mbostock** [comment]
Cool demonstration! Thank you.
